version: '3.3'

services:
  localstack:
    image: "localstack/localstack"
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    ports:
      # dynamodbの4566やlambdaやsqsの4571をまとめて開放する
      - "4566-4599:4566-4599"
      - "8055:8080"
#      - "127.0.0.1:8055:8080"
#      - "4566:4566"
#      - "4571:4571"
#      - "8080:8080"
    environment:
      DEFAULT_REGION: ap-northeast-1
#      SERVICES: "dynamodb,sqs,lambda,events,stepfunctions"
      SERVICES: ${SERVICES- }
      DEBUG: 1
      DATA_DIR: /tmp/localstack-data
      PORT_WEB_UI: 8090
      LAMBDA_REMOTE_DOCKER: false
      LAMBDA_EXECUTOR: docker-reuse
      KINESIS_ERROR_PROBABILITY: ${KINESIS_ERROR_PROBABILITY- }
      DOCKER_HOST: "unix:///var/run/docker.sock"
      HOST_TMP_FOLDER: ${TMPDIR}
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-local}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-local}
      AWS_DEFAULT_REGION: ${AWS_REGION:-local}
    networks:
      - "local"
    volumes:
      - ./localstackData:/tmp/localstack-data
      - "/var/run/docker.sock:/var/run/docker.sock"

  # 下記のやり方だとdynamodb-adminでエラーになるのでコメントアウト
  #  localstack:
  #    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  #    image: localstack/localstack
  #    network_mode: bridge
  #    ports:
  #      - "4566:4566"
  #      - "4571:4571"
  #      - "8080:8080"
  #    environment:
  #      - DEFAULT_REGION=ap-northeast-1
  #      # - SERVICES=${SERVICES- }
  #      - SERVICES=lambda, sqs, sns, events, stepfunctions
  #      # - DEBUG=${DEBUG- }
  #      - DEBUG=1
  #      - DATA_DIR=/tmp/localstack/data
  #      - PORT_WEB_UI=${PORT_WEB_UI- }
  #      - LAMBDA_EXECUTOR=docker-reuse
  #      - LAMBDA_REMOTE_DOCKER=false
  #      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
  #      - DOCKER_HOST=unix:///var/run/docker.sock
  #      - HOST_TMP_FOLDER=${TMPDIR}
  #    volumes:
  #      - "./localstackData:/tmp/localstack"
  #      - "/var/run/docker.sock:/var/run/docker.sock"
  #    networks:
  #      - "local"

  dynamodb-admin:
    image: "aaronshaf/dynamodb-admin:latest"
    container_name: "dynamodb-viewer"
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: http://localstack:4566
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-local}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-local}
    depends_on:
      - "localstack"
    networks:
      - "local"

# localstackに移行するのでコメントアウト
#  dynamodb-persistent:
#    container_name: dynamodb-persistent
#    image: amazon/dynamodb-local
#    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
#    networks:
#      - dynamodb-network
#    ports:
#      - '8000:8000'
#    volumes:
#      - ./localDynamodbData:/home/dynamodblocal/data

#  dynamodb-admin:
#    container_name: dynamodb-admin
#    image: aaronshaf/dynamodb-admin
#    environment:
#      DYNAMO_ENDPOINT: http://dynamodb-persistent:8000
#    ports:
#      - '8001:8001'
#    networks:
#      - local

networks:
  local:
    driver: 'bridge'

