version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-typescript"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-j111qjrdhpr2"
s3_prefix = "lambda-typescript"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
