name: Staging Deploy

on:
  push:
    branches:
      - feature/staging
env:
  REGION: ap-northeast-1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    env:
      AWS_ROLE_ARN_SECRETS: ${{ secrets.AWS_ROLE_ARN }}
    steps:
      - name: Get AWS Credentials Using OIDC
        id: aws_sts_creds
        run: |
          echo "${{ toJson(secrets) }}"
          echo "${{ env.AWS_ROLE_ARN }}"
          export AWS_ROLE_ARN=${{ env.AWS_ROLE_ARN_SECRETS }}
          export AWS_WEB_IDENTITY_TOKEN_FILE=/tmp/awscreds
          export AWS_DEFAULT_REGION=${{ env.REGION }}

          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value' > $AWS_WEB_IDENTITY_TOKEN_FILE

          aws sts assume-role-with-web-identity \
            --role-arn $AWS_ROLE_ARN \
            --role-session-name github-actions \
            --web-identity-token file://$AWS_WEB_IDENTITY_TOKEN_FILE \
            --duration-seconds 1000 > /tmp/aws-creds

          export AWS_ACCESS_KEY_ID="$(cat /tmp/aws-creds | jq -r ".Credentials.AccessKeyId")"
          export AWS_SECRET_ACCESS_KEY="$(cat /tmp/aws-creds | jq -r ".Credentials.SecretAccessKey")"
          export AWS_SESSION_TOKEN="$(cat /tmp/aws-creds | jq -r ".Credentials.SessionToken")"

          echo ::add-mask::$AWS_ACCESS_KEY_ID
          echo ::add-mask::$AWS_SECRET_ACCESS_KEY
          echo ::add-mask::$AWS_SESSION_TOKEN

          echo ::set-output name=aws_access_key_id::$AWS_ACCESS_KEY_ID
          echo ::set-output name=aws_secret_access_key::$AWS_SECRET_ACCESS_KEY
          echo ::set-output name=aws_session_token::$AWS_SESSION_TOKEN
          echo ::set-output name=aws_default_region::$AWS_DEFAULT_REGION

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.aws_sts_creds.outputs.aws_access_key_id }}
          aws-secret-access-key: ${{ steps.aws_sts_creds.outputs.aws_secret_access_key }}
          aws-session-token: ${{ steps.aws_sts_creds.outputs.aws_session_token }}
          aws-region: ${{ steps.aws_sts_creds.outputs.aws_default_region }}

      - name: SAM Build
        run: sam --version
